Version: 1.00

Location:
    # list of qualif_dirs to be searched for sample manifest files
    sources:
        -
            path: /mnt/researchsan02a/Sample_Manifests/ECHO # /mnt/researchsan02a/Projects/ECHO/SampleInfo

    # path to the folder where application level log files are located (one per application run)
    app_logs: logs
    
    ignore_files:
        - ".DS_Store"
        - "Thumbs.db"

Manifest:
    folder_name: ManifestsToProcess # SampleManifests
    config_file_name: manifest_config.yaml

Validate:
    # list of sections and fields that the application will validate in the config file
    # if no definitions for listed fields found, the app will fail the config file validation
    manifest_config_fields:
        - Database:
              - {name: study_id, required: True}
        - Fields:
            - {name: aliquot_id, required: True}
            - {name: sample_id, required: True}
            - {name: creation_date, required: False}
            - {name: volume, required: False}
            - {name: num_cells, required: False}
            - {name: species, required: False}
            - {name: tissue, required: False}
            - {name: specimen_prep, required: False}
            - {name: ship_date, required: False}


Logging:
    #main log - log created by the main application

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO
    # inquiry_log_level: INFO

Email:
    #default settings for sending emails
    smtp_server: smtp.mssm.edu
    smtp_server_port: 25
    default_from_email: stasrirak.ms@gmail.com
    send_to_emails: stasrirak.ms@gmail.com
    send_emails: True # expected values: True, False

Database:
    connection:
        #dev conn string: Driver={SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@lc
        #prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.160.20.65\SSQL_2016;Database=dw_motrpac;UID=mt_internal_user;PWD=se@lf0n1nt3rn@lc
        #    #DB connection string
        mdb_conn_str: DRIVER={ODBC Driver 17 for SQL Server};SERVER=10.160.20.65,51261;DATABASE=dw_motrpac;UID=mt_internal_user;PWD=se@lf0n1nt3rn@l

    procedure:
        # name of the stored proc to be used to load samples to DB
        load_manifest_record: exec usp_add_aliquot_manifest_data @aliquot_id = '{aliquot_id}',  @sample_id ='{sample_id}', @study_id = {study_id}, @manifest_data ='{@manifest_data}', @source_name='{source_name}', @output_status_dataset = 1

    manifest:
        expected_aliquot_id_name: aliquot_id
        expected_sample_id_name: sample_id

