Version: 1.00

Location:
    # list of qualif_dirs to be searched for sample manifest files
    sources:
        -
            path: D:\MounSinai\Darpa\Programming\Manifest_Data_Reader\datasource_examples\J_Drive\ECHO\SampleInfo\HIV
        -
            path: D:\MounSinai\Darpa\Programming\Manifest_Data_Reader\datasource_examples\J_Drive\ECHO\SampleInfo\HLTH
            Manifest:
                folder_name: SampleManifests1
                config_file_name: manifest_config1.yaml
        -
            path: D:\MounSinai\Darpa\Programming\Manifest_Data_Reader\datasource_examples\J_Drive\ECHO

    # path to the folder where application level log files are located (one per application run)
    app_logs: D:\MounSinai\Darpa\Programming\Manifest_Data_Reader\logs

Manifest:
    folder_name: SampleManifests
    config_file_name: manifest_config.yaml
    # TODO: add validation requirements for a manifest config file
    config_validation:


Logging:
    #main log - log created by the main application
    #inquiry log - log created for each processed inquiry

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO
    # inquiry_log_level: INFO

Email:
    #default settings for sending emails
    smtp_server: smtp.mssm.edu
    smtp_server_port: 25
    default_from_email: stasrirak.ms@gmail.com
    send_to_emails: stasrirak.ms@gmail.com, stasrira@yahoo.com
    send_emails: True # expected values: True, False

# Execute:
    # if set to true, data downloader file (Location/data_downloader_path) will be executed upon completion
    # of processing inquiries
    # run_data_downloader: True

Validate:
    # if set to True, provided inquiry values will be validated against corresponded entries in the dict_config.yaml
    # inquiry_values_vs_dictionary: True

Database:
    connection:
        #dev conn string: Driver={SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l
        #prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.160.20.65\SSQL_2016;Database=dw_motrpac;UID=mt_internal_user;PWD=se@lf0n1nt3rn@l
        #    #DB connection string
        mdb_conn_str: Driver={ODBC Driver 17 for SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;UID=mt_internal_user;PWD=se@lf0n1nt3rn@l # Driver={SQL Server};Server=localhost\sqlexpress;Database=dw_motrpac;User=mt_internal_user;Password=se@lf0n1nt3rn@l

    procedure:
        # name of the stored proc to be used to load samples to DB
        load_manifest_record: exec usp_add_aliquot_manifest_data @aliquot_id = '{aliquot_id}',  @sample_id ='{sample_id}', @study_id = {study_id}, @manifest_data ='{@manifest_data}', @source_name='{source_name}', @output_status_dataset = 1

    manifest:
        expected_aliquot_id_name: aliquot_id
        expected_sample_id_name: sample_id

